name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - sandbox

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'github-pages' || 'Sandbox-Env' }}
      url: ${{ steps.deployment.outputs.page_url }}${{ github.ref == 'refs/heads/sandbox' && 'sandbox/' || '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Deployment Directory
        run: |
          mkdir -p deploy_out/sandbox
          
          # 1. Export Main to root (Always keep Main up-to-date)
          git checkout main
          cp -a www/. deploy_out/
          
          # 2. Export Sandbox to /sandbox (Always keep Sandbox up-to-date)
          git checkout sandbox
          cp -a www/. deploy_out/sandbox/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy_out/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
